name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache-dependency-path: yarn.lock
          
      - name: Build
        run: yarn && yarn run build
      
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan ${remote_host} >> /home/runner/.ssh/known_hosts
            echo "${remote_key}" > /home/runner/.ssh/id_rsa
            chmod 600 /home/runner/.ssh/id_rsa
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null   
            ssh-add /home/runner/.ssh/id_rsa

      - name: Deploy via Rsync
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          local_dir: ./dist/
          remote_dir: ${{ secrets.DEPLOY_DIRECTORY }}
        run: |
          rsync -avzr --delete ${local_dir} ${remote_user}@${remote_host}:${remote_dir}          
